# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x65vice_service.proto\x12\x05\x66leet\"$\n\x0fRegisterRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"H\n\x0e\x44\x65viceResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.fleet.DeviceStatus\"7\n\rActionRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63tion_type\x18\x02 \x01(\t\"#\n\x0e\x41\x63tionResponse\x12\x11\n\taction_id\x18\x01 \x01(\t\"(\n\x13\x41\x63tionStatusRequest\x12\x11\n\taction_id\x18\x01 \x01(\t\"&\n\x14\x41\x63tionStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t*&\n\x0c\x44\x65viceStatus\x12\x08\n\x04IDLE\x10\x00\x12\x0c\n\x08UPDATING\x10\x01\x32\xea\x01\n\x10\x44\x65viceManagement\x12?\n\x0eRegisterDevice\x12\x16.fleet.RegisterRequest\x1a\x15.fleet.DeviceResponse\x12\x43\n\x14InitiateDeviceAction\x12\x14.fleet.ActionRequest\x1a\x15.fleet.ActionResponse\x12P\n\x15GetDeviceActionStatus\x12\x1a.fleet.ActionStatusRequest\x1a\x1b.fleet.ActionStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICESTATUS']._serialized_start=319
  _globals['_DEVICESTATUS']._serialized_end=357
  _globals['_REGISTERREQUEST']._serialized_start=31
  _globals['_REGISTERREQUEST']._serialized_end=67
  _globals['_DEVICERESPONSE']._serialized_start=69
  _globals['_DEVICERESPONSE']._serialized_end=141
  _globals['_ACTIONREQUEST']._serialized_start=143
  _globals['_ACTIONREQUEST']._serialized_end=198
  _globals['_ACTIONRESPONSE']._serialized_start=200
  _globals['_ACTIONRESPONSE']._serialized_end=235
  _globals['_ACTIONSTATUSREQUEST']._serialized_start=237
  _globals['_ACTIONSTATUSREQUEST']._serialized_end=277
  _globals['_ACTIONSTATUSRESPONSE']._serialized_start=279
  _globals['_ACTIONSTATUSRESPONSE']._serialized_end=317
  _globals['_DEVICEMANAGEMENT']._serialized_start=360
  _globals['_DEVICEMANAGEMENT']._serialized_end=594
# @@protoc_insertion_point(module_scope)
